
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: monitoring-dashboard
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events { worker_connections 1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      sendfile on;
      keepalive_timeout 65;

      server {
        listen 80;
        root /usr/share/nginx/html;

        location / { try_files $uri /index.html; }

        location /api/ {
          proxy_pass http://backend-svc.monitoring-dashboard.svc.cluster.local:8080/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
