apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monitoring-dashboard
  labels: { app: frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: frontend-nginx-config
            items: [{ key: nginx.conf, path: nginx.conf }]
      containers:
        - name: frontend
          image: ghcr.io/YOUR_GH_USER/metrics-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "128Mi" }
